import 'animate.css'
import 'normalize.css'
import 'src/style/markdown.css'
import 'src/style/variable.css'
import 'src/style/reset.css'
import 'src/style/global.css'
import { Metadata } from 'next'
import BackTop from 'src/components/BackTop'
import Provider from 'src/components/Provider'
import Header from 'src/components/header'
import AppConfig from 'src/config/app'
import StyledJsxRegistry from 'src/lib/registry'
export const metadata: Metadata = {
  title: 'oh-my-note',
  description: 'Generated by create next app',
  icons: [
    {
      rel: 'apple-touch-icon',
      url: '/favicon/57x57.png',
      type: 'image/png',
      sizes: '57x57',
    },
    {
      rel: 'apple-touch-icon',
      url: '/favicon/76x76.png',
      type: 'image/png',
      sizes: '76x76',
    },
    {
      rel: 'apple-touch-icon',
      url: '/favicon/120x120.png',
      type: 'image/png',
      sizes: '120x120',
    },
    {
      rel: 'apple-touch-icon',
      url: '/favicon/180x180.png',
      type: 'image/png',
      sizes: '180x180',
    },
  ],
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const nav = await getNavigation()
  return (
    <html lang="en">
      <body>
        <StyledJsxRegistry>
          <Provider>
            <Header nav={nav} />
            {children}
            <BackTop />
          </Provider>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}

async function getNavigation() {
  return AppConfig.navigation
}
